apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-node
  namespace: infra
spec:
  concurrencyPolicy: Forbid
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          namespace: infra
        spec:
          containers:
            - image: bitnami/rclone
              imagePullPolicy: IfNotPresent
              name: rclone
              args:
                - copy 
                - /local/ 
                - /nfs
                - --exclude "replorigin_checkpoint"
                - -v
              volumeMounts:
                - mountPath: /local
                  name: local
                  readOnly: true
                - mountPath: /nfs
                  name: nfs
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            allowPrivilegeEscalation: true
          volumes:
            - name: local
              hostPath:
                path: /home/homesys/apps
                type: Directory
            - name: nfs
              hostPath:
                path: /mnt/fileserver/backups/rke2
                type: Directory
      backoffLimit: 2