apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-node
  namespace: infra
spec:
  concurrencyPolicy: Forbid
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          namespace: infra
        spec:
          containers:
            - image: bitnami/rclone
              imagePullPolicy: IfNotPresent
              name: rclone
              command: ["/bin/sh", "-c"]
              args:
                - "rclone sync /local/ /nfs --exclude=*/replorigin_checkpoint --exclude=*/pg_internal.init --exclude=*/influxd.bolt --exclude=db/influxdb --create-empty-src-dirs -v"
              # args:
                # - "backup_timestamp=$(date +'%Y%m%d_%H%M%S'); rclone sync /local/ /nfs --exclude=*/replorigin_checkpoint --backup-dir=/old --suffix=_$backup_timestamp --suffix-keep-extension --create-empty-src-dirs -v"
              volumeMounts:
                - mountPath: /local
                  name: local
                  readOnly: true
                - mountPath: /nfs
                  name: nfs
                - mountPath: /old
                  name: old
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            allowPrivilegeEscalation: true
          volumes:
            - name: local
              hostPath:
                path: /home/homesys/apps
                type: Directory
            - name: nfs
              hostPath:
                path: /mnt/fileserver/backups/rke2
                type: Directory
            - name: old
              hostPath:
                path: /mnt/fileserver/backups/rke2-old
                type: Directory
      backoffLimit: 2