apiVersion: batch/v1
kind: Job
metadata:
  name: copy-immich-uploads
  namespace: home
spec:
  template:
    metadata:
      namespace: home
    spec:
      containers:
        - image: bitnami/rclone
          imagePullPolicy: IfNotPresent
          name: rclone
          args:
            - copy 
            - /nfs/ 
            - /longhorn/uploads
          volumeMounts:
            - mountPath: /nfs
              name: nfs
              readOnly: true
            - mountPath: /longhorn
              name: longhorn
      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        allowPrivilegeEscalation: true
      volumes:
        - name: nfs
          hostPath:
            path: /mnt/fileserver/apps/immich/uploads
            type: Directory
        - name: longhorn
          persistentVolumeClaim:
            claimName: immich-longhorn
  backoffLimit: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  name: copy-immich-models-typesense
  namespace: home
spec:
  template:
    metadata:
      namespace: home
    spec:
      containers:
        - image: bitnami/rclone
          imagePullPolicy: IfNotPresent
          name: rclone
          args:
            - copy 
            - /nfs/ 
            - /local
          volumeMounts:
            - mountPath: /nfs/models
              name: models
              readOnly: true
            - mountPath: /nfs/typesense
              name: typesense
              readOnly: true
            - mountPath: /local
              name: local
      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        allowPrivilegeEscalation: true
      volumes:
        - name: models
          hostPath:
            path: /mnt/fileserver/apps/immich/models
            type: Directory
        - name: typesense
          hostPath:
            path: /mnt/fileserver/apps/immich/typesense
            type: Directory
        - name: local
          persistentVolumeClaim:
            claimName: immich-local
  backoffLimit: 2