apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: home
  labels:
    app.kubernetes.io/name: immich
data:
  TZ: "Australia/Perth"
  NODE_ENV: "production"
  DB_DATABASE_NAME: immich
  DB_PORT: '5432'
  IMMICH_WEB_URL: http://immich-web.home.svc.cluster.local:3000
  IMMICH_SERVER_URL: http://immich-server.home.svc.cluster.local:3001
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.home.svc.cluster.local:3003
  MACHINE_LEARNING_PORT: '3003'
  TYPESENSE_HOST: immich-typesense.home.svc.cluster.local
  TYPESENSE_DATA_DIR: /config