defaultNamespace: infra

helm:
  chart: grafana

  repo: https://grafana.github.io/helm-charts

  releaseName: grafana
  # Makes helm skip the check for its own annotations
  takeOwnership: true
  # The version of the chart or semver constraint of the chart to find. If a constraint
  # is specified it is evaluated each time git changes.
  # The version also determines which chart to download from OCI registries.
  version: 6.58.6
  # Any values that should be placed in the `values.yaml` and passed to helm during
  # install.
  values:
    testFramework:
      enabled: false
    ingress:
      enabled: true 
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - grafana.ocelotspot.com
      tls:
        - hosts:
            - grafana.ocelotspot.com
          secretName: "grafana.ocelotspot.com-tls"
    env:
      GF_EXPLORE_ENABLED: true
    persistence:
      enabled: true 
      existingClaim: grafana-local
    admin:
      existingSecret: grafana-secrets
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
    plugins:
      - natel-discrete-panel
      - pr0ps-trackmap-panel
      - grafana-piechart-panel
      - vonage-status-panel
      - grafana-worldmap-panel
      - grafana-clock-panel
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            url: https://loki.ocelotspot.com:3100
            access: proxy
        deleteDatasources:
          - name: Loki
            orgId: 1
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        loki-logs:
          datasource: Loki
          gnetId: 12019
          revision: 2
    grafana.ini:
      server:
        root_url: "https://grafana.ocelotspot.com"
        enable_gzip: true
      users:
        allow_sign_up: false
  # Override immutable resources. This could be dangerous.
  force: false
  # Set the Helm --atomic flag when upgrading
  atomic: false
  # Disable go template pre-processing on the fleet values
  disablePreProcess: false
  # if set and timeoutSeconds provided, will wait until all Jobs have been completed before marking the GitRepo as ready.
  # It will wait for as long as timeoutSeconds
  waitForJobs: true

# dependsOn allows you to configure dependencies to other bundles. The current bundle
# will only be deployed, after all dependencies are deployed and in a Ready state.
dependsOn:
  # Format: <GITREPO-NAME>-<BUNDLE_PATH> with all path separators replaced by "-"
  # Example: GitRepo name "one", Bundle path "/multi-cluster/hello-world" => "one-multi-cluster-hello-world"
  # Note: Bundle names are limited to 53 characters long. If longer they will be shortened:
  # opni-fleet-examples-fleets-opni-ui-plugin-operator-crd becomes opni-fleet-examples-fleets-opni-ui-plugin-opera-021f7
  - name: homesys-services-networking-metallb-custom
  - name: homesys-services-storage-filepaths
  # Select bundles to depend on based on their label.
  # - selector:
  #     matchLabels:
  #       app: weak-monkey

# A paused bundle will not update downstream clusters but instead mark the bundle
# as OutOfSync. One can then manually confirm that a bundle should be deployed to
# the downstream clusters.
# Default: false
paused: false