defaultNamespace: infra

helm:
  chart: reloader

  repo: https://stakater.github.io/stakater-charts

  releaseName: reloader
  # Makes helm skip the check for its own annotations
  takeOwnership: true
  # The version of the chart or semver constraint of the chart to find. If a constraint
  # is specified it is evaluated each time git changes.
  # The version also determines which chart to download from OCI registries.
  version: 1.0.30
  # Any values that should be placed in the `values.yaml` and passed to helm during
  # install.
  values:
    reloader:
      reloadStrategy: annotations

# dependsOn allows you to configure dependencies to other bundles. The current bundle
# will only be deployed, after all dependencies are deployed and in a Ready state.
dependsOn:
  # Format: <GITREPO-NAME>-<BUNDLE_PATH> with all path separators replaced by "-"
  # Example: GitRepo name "one", Bundle path "/multi-cluster/hello-world" => "one-multi-cluster-hello-world"
  # Note: Bundle names are limited to 53 characters long. If longer they will be shortened:
  # opni-fleet-examples-fleets-opni-ui-plugin-operator-crd becomes opni-fleet-examples-fleets-opni-ui-plugin-opera-021f7
  - name: homesys-services-networking-metallb-custom
  - name: homesys-services-storage-filepaths
  - name: homesys-services-tasks-jobs-first-build
  # Select bundles to depend on based on their label.
  # - selector:
  #     matchLabels:
  #       app: weak-monkey

# A paused bundle will not update downstream clusters but instead mark the bundle
# as OutOfSync. One can then manually confirm that a bundle should be deployed to
# the downstream clusters.
# Default: false
paused: true