apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: joplin
  name: joplin
  namespace: home
spec:
  selector:
    app.kubernetes.io/name: joplin
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: joplin
  name: joplin
  namespace: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: joplin
  serviceName: joplin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: joplin
      name: joplin
    spec:
      containers:
        - name: joplin
          image: joplin/server:latest
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: joplin-creds
                  key: db-host
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: joplin-creds
                  key: db-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: joplin-creds
                  key: db-pass
            - name: POSTGRES_DB
              value: joplin
            - name: DB_CLIENT
              value: pg
            - name: POSTGRES_PORT
              value: '5432'
            - name: APP_PORT
              value: '80'
            - name: APP_BASE_URL
              value: "https://jopps.ocelotspot.com"
      securityContext:
        # runAsUser: 1001
        # runAsGroup: 1001
        # fsGroup: 1001
        allowPrivilegeEscalation: true
