apiVersion: v1
kind: PersistentVolume
metadata:
  name: homer-local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/tera/vols/homer
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homesys
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-local
  namespace: home
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: homer-local
  storageClassName: local-storage