---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-coredns
  namespace: kube-system
spec:
  valuesContent: |-
    autoscaler:
      resources:
        requests:
          cpu: "10m"
    resources:
      requests:
        cpu: "50m"