apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-node-postgresql
  namespace: infra
spec:
  concurrencyPolicy: Forbid
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          namespace: infra
        spec:
          containers:
            - image: bitnami/rclone
              imagePullPolicy: IfNotPresent
              name: rclone
              command: ["/bin/sh", "-c"]
              args:
                - "rclone sync /local/ /nfs --exclude=*/replorigin_checkpoint --exclude=*/pg_internal.init --create-empty-src-dirs -v"
              # args:
                # - "backup_timestamp=$(date +'%Y%m%d_%H%M%S'); rclone sync /local/ /nfs --exclude=*/replorigin_checkpoint --backup-dir=/old --suffix=_$backup_timestamp --suffix-keep-extension --create-empty-src-dirs -v"
              volumeMounts:
                - mountPath: /local
                  name: local
                  readOnly: true
                - mountPath: /nfs
                  name: nfs
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            fsGroup: 1001
            allowPrivilegeEscalation: true
          volumes:
            - name: local
              hostPath:
                path: /mnt/tera/vols/postgresql
                type: Directory
            - name: nfs
              hostPath:
                path: /mnt/fileserver/backups/rke2/db/postgresql
                type: Directory
      backoffLimit: 2