apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudbeaver-local-logs
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/tera/vols/cloudbeaver/logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homesys
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudbeaver-local-logs
  namespace: home
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: cloudbeaver-local-logs
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudbeaver-local-workspace
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/tera/vols/cloudbeaver/workspace
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homesys
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudbeaver-local-workspace
  namespace: home
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: cloudbeaver-local-workspace
  storageClassName: local-storage