apiVersion: batch/v1
kind: Job
metadata:
  name: copy-homebox-data
  namespace: home
spec:
  template:
    metadata:
      namespace: home
    spec:
      containers:
        - image: bitnami/rclone
          imagePullPolicy: IfNotPresent
          name: rclone
          args:
            - copy 
            - /nfs/ 
            - /local/sqlite
            - -v
          volumeMounts:
            - mountPath: /nfs
              name: nfs
              readOnly: true
            - mountPath: /local
              name: local
      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        allowPrivilegeEscalation: true
      volumes:
        - name: nfs
          hostPath:
            path: /mnt/fileserver/databases/sqlite/homebox
            type: Directory
        - name: local
          existingVolumeClaim: homebox-local
  backoffLimit: 2