apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-longhorn
spec:
  capacity:
    storage: 300Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '1'
      staleReplicaTimeout: '20'
    volumeHandle: immich-longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-longhorn
  namespace: home
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  volumeName: immich-longhorn
  storageClassName: longhorn-static
