apiVersion: v1
kind: PersistentVolume
metadata:
  name: scripts
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '1'
      staleReplicaTimeout: '20'
    volumeHandle: scripts
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scripts
  namespace: infra
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: scripts
  storageClassName: longhorn-static
