apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: gwyn@hannay.id.au
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
        name: letsencrypt-staging
    solvers:
      - selector:
          dnsZones:
            - "ocelotspot.com"
        dns01:
          cloudflare:
            email: gwyn@hannay.id.au
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token