defaultNamespace: longhorn-system

helm:
  chart: longhorn

  repo: https://charts.longhorn.io

  releaseName: longhorn
  # Makes helm skip the check for its own annotations
  takeOwnership: false
  # The version of the chart or semver constraint of the chart to find. If a constraint
  # is specified it is evaluated each time git changes.
  # The version also determines which chart to download from OCI registries.
  version: 1.5.0
  # Any values that should be placed in the `values.yaml` and passed to helm during
  # install.
  values:
    persistence:
      defaultClassReplicaCount: 1
      reclaimPolicy: Retain
    csi:
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1
    defaultSettings:
      defaultLonghornStaticStorageClass: longhorn-static
      defaultReplicaCount: 1
      guaranteedEngineManagerCPU: 5
      guaranteedReplicaManagerCPU: 5
    longhornUI:
      replicas: 1
    ingress:
      enabled: true
      host: files.ocelotspot.com
      tls: true
      secureBackends: true
      tlsSecret: files.ocelotspot.com-tls
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Block Storage
        gethomepage.dev/group: homesys
        gethomepage.dev/icon: longhorn.png
        gethomepage.dev/name: Longhorn
  # Override immutable resources. This could be dangerous.
  force: false
  # Set the Helm --atomic flag when upgrading
  atomic: false
  # Disable go template pre-processing on the fleet values
  disablePreProcess: false
  # if set and timeoutSeconds provided, will wait until all Jobs have been completed before marking the GitRepo as ready.
  # It will wait for as long as timeoutSeconds
  waitForJobs: true

# dependsOn allows you to configure dependencies to other bundles. The current bundle
# will only be deployed, after all dependencies are deployed and in a Ready state.
dependsOn:
  # Format: <GITREPO-NAME>-<BUNDLE_PATH> with all path separators replaced by "-"
  # Example: GitRepo name "one", Bundle path "/multi-cluster/hello-world" => "one-multi-cluster-hello-world"
  # Note: Bundle names are limited to 53 characters long. If longer they will be shortened:
  # opni-fleet-examples-fleets-opni-ui-plugin-operator-crd becomes opni-fleet-examples-fleets-opni-ui-plugin-opera-021f7
  # - name: homesys-services-external-dns
  # Select bundles to depend on based on their label.
  # - selector:
  #     matchLabels:
  #       app: weak-monkey

diff:
  comparePatches:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: engineimages.longhorn.io
    operations:
    - op: remove
      path: /status
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: nodes.longhorn.io
    operations:
    - op: remove
      path: /status
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: volumes.longhorn.io
    operations:
    - op: remove
      path: /status