apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
  namespace: infra
  labels:
    app.kubernetes.io/name: vector
data:
  aggregator.yaml: |
    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 0.0.0.0:8686
    sources:
      kubernetes_logs:
        type: vector
        address: 0.0.0.0:6000
        version: "2"
    transforms:
      kubernetes_logs_remaps:
        type: remap
        inputs:
          - kubernetes_logs
        source: |
          # Standardize 'app' index
          .custom_app_name = .pod_labels."app.kubernetes.io/name" || .pod_labels.app || .pod_labels."k8s-app" || "unknown"
    sinks:
      kubernetes_sink:
        type: loki
        inputs: [kubernetes_logs_remaps]
        endpoint: http://loki.infra.svc.cluster.local:3100
        encoding:
          codec: json
        out_of_order_action: accept
        labels:
          app: '{{ custom_app_name }}'
          k8s_container: '{{ kubernetes.container_name }}'
          k8s_filename: '{{ kubernetes.file }}'
          k8s_instance: '{{ kubernetes.pod_labels."app.kubernetes.io/instance" }}'
          k8s_namespace: '{{ kubernetes.pod_namespace }}'
          k8s_node: '{{ kubernetes.pod_node_name }}'
          k8s_pod: '{{ kubernetes.pod_name }}'