apiVersion: batch/v1
kind: Job
metadata:
  name: check-filepaths-homebox
  namespace: infra
spec:
  template:
    metadata:
      namespace: infra
    spec:
      containers:
        - name: homebox
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - ls /local/
          volumeMounts:
            - mountPath: /nfs
              name: nfs
              readOnly: true
            - mountPath: /local
              name: local
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 1001
      volumes:
        - name: nfs
          hostPath:
            path: /mnt/fileserver
            type: Directory
        - name: local
          hostPath:
            path: /mnt/tera/vols/homebox
            type: Directory
  backoffLimit: 3