apiVersion: batch/v1
kind: Job
metadata:
  name: copy-paperless-data
  namespace: home
spec:
  template:
    metadata:
      namespace: home
    spec:
      containers:
        - image: bitnami/rclone
          imagePullPolicy: IfNotPresent
          name: rclone
          args:
            - copy 
            - /nfs/ 
            - /local/data
            - -v
          volumeMounts:
            - mountPath: /nfs
              name: nfs
              readOnly: true
            - mountPath: /local
              name: local
      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        allowPrivilegeEscalation: true
      volumes:
        - name: nfs
          hostPath:
            path: /mnt/fileserver/apps/paperless/data
            type: Directory
        - name: local
          existingVolumeClaim: paperless-local
  backoffLimit: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  name: copy-paperless-media
  namespace: home
spec:
  template:
    metadata:
      namespace: home
    spec:
      containers:
        - image: bitnami/rclone
          imagePullPolicy: IfNotPresent
          name: rclone
          args:
            - copy 
            - /nfs/ 
            - /longhorn/media
            - -v
          volumeMounts:
            - mountPath: /nfs
              name: nfs
              readOnly: true
            - mountPath: /longhorn
              name: longhorn
      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        allowPrivilegeEscalation: true
      volumes:
        - name: nfs
          hostPath:
            path: /mnt/fileserver/apps/paperless/media
            type: Directory
        - name: longhorn
          existingVolumeClaim: paperless-longhorn
  backoffLimit: 2