apiVersion: batch/v1
kind: Job
metadata:
  name: copy-paperless
  namespace: home
spec:
  template:
    metadata:
      namespace: home
    spec:
      containers:
        - image: bitnami/rclone
          imagePullPolicy: IfNotPresent
          name: rclone
          args:
            - copy 
            - /nfs/ 
            - /longhorn/data
            - -v
          # securityContext:
          #   runAsUser: 1001
          #   runAsGroup: 1001
          #   fsGroup: 1001
          volumeMounts:
            - mountPath: /nfs
              name: nfs
              readOnly: true
            - mountPath: /longhorn
              name: longhorn
      restartPolicy: Never
      volumes:
        - hostPath:
            path: /mnt/fileserver/apps/paperless/data
            type: Directory
          name: nfs
        - name: longhorn
          persistentVolumeClaim:
            claimName: paperless
  backoffLimit: 3