apiVersion: batch/v1
kind: Job
metadata:
  name: rclone-job-try
  namespace: infra
spec:
  template:
    metadata:
      namespace: infra
    spec:
      containers:
        - image: bitnami/rclone
          imagePullPolicy: IfNotPresent
          name: rclone
          args:
            - copy 
            - /nfs/ 
            - /longhorn
          volumeMounts:
            - mountPath: /nfs
              name: nfs
              readOnly: true
            - mountPath: /longhorn
              name: longhorn
      restartPolicy: Never
      volumes:
        - hostPath:
            path: /mnt/fileserver/rke2
            type: Directory
          name: nfs
        - name: longhorn
          persistentVolumeClaim:
            claimName: fileserver
  backoffLimit: 3