apiVersion: v1
kind: ConfigMap
metadata:
  name: wallabag-config
  namespace: home
  labels:
    app.kubernetes.io/name: wallabag
data:
  TZ: "Australia/Perth"
  PHP_TIMEZONE: "Australia/Perth"
  SYMFONY__ENV__DATABASE_DRIVER: pdo_pgsql
  SYMFONY__ENV__DATABASE_NAME: wallabag
  SYMFONY__ENV__DATABASE_PORT: '5432'
  SYMFONY__ENV__DOMAIN_NAME: https://reading.ocelotspot.com
  SYMFONY__ENV__SERVER_NAME: Wallabag
  POPULATE_DATABASE: 'false'