apiVersion: v1
kind: PersistentVolume
metadata:
  name: homer-longhorn
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '1'
      staleReplicaTimeout: '20'
    volumeHandle: homer-longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-longhorn
  namespace: home
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: homer-longhorn
  storageClassName: longhorn-static
