apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: home
  name: home
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: infra
  name: infra
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: data
  name: data