apiVersion: batch/v1
kind: Job
metadata:
  name: copy-wallabag-images
  namespace: home
spec:
  template:
    metadata:
      namespace: home
    spec:
      containers:
        - image: bitnami/rclone
          imagePullPolicy: IfNotPresent
          name: rclone
          args:
            - copy 
            - /nfs/ 
            - /longhorn/images
          volumeMounts:
            - mountPath: /nfs
              name: nfs
              readOnly: true
            - mountPath: /longhorn
              name: longhorn
      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        allowPrivilegeEscalation: true
      volumes:
        - name: nfs
          hostPath:
            path: /mnt/fileserver/apps/wallabag/images
            type: Directory
        - name: longhorn
          persistentVolumeClaim:
            claimName: wallabag-longhorn
  backoffLimit: 2