# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: homebox-local
# spec:
#   capacity:
#     storage: 10Gi
#   volumeMode: Filesystem
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: local-storage
#   local:
#     path: /home/practice/apps/homebox
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - practice
#           - homesys
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebox-local
  namespace: home
  annotations:
    volumeType: hostPath
spec:
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # volumeName: homebox-local
  storageClassName: local-path