apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-local-cache
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/homesys/apps/immich/models
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - practice
          - homesys
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-local-cache
  namespace: home
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: immich-local-cache
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-local-config
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/homesys/apps/immich/typesense
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - practice
          - homesys
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-local-config
  namespace: home
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: immich-local-config
  storageClassName: local-storage