apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/practice/apps/immich
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - practice
          - homesys
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich
  namespace: home
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: immich
  storageClassName: local-storage