apiVersion: batch/v1
kind: Job
metadata:
  name: copy-paperless
  namespace: home
spec:
  template:
    metadata:
      namespace: home
    spec:
      containers:
        - image: bitnami/rclone
          imagePullPolicy: IfNotPresent
          name: rclone
          args:
            - copy 
            - /nfs/ 
            - /local/data
            - -v
          volumeMounts:
            - mountPath: /nfs
              name: nfs
              readOnly: true
            - mountPath: /local
              name: local
      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        allowPrivilegeEscalation: true
      volumes:
        - hostPath:
            path: /mnt/fileserver/apps/paperless/data
            type: Directory
          name: nfs
        - name: local
          hostPath:
            path: /home/practice/sqlite/paperless
            type: Directory
  backoffLimit: 3