apiVersion: batch/v1
kind: Job
metadata:
  name: copy-homer-files
  namespace: home
spec:
  template:
    metadata:
      namespace: home
    spec:
      containers:
        - image: bitnami/rclone
          imagePullPolicy: IfNotPresent
          name: rclone
          args:
            - copy 
            - /nfs/ 
            - /longhorn
            - -v
          volumeMounts:
            - mountPath: /nfs
              name: nfs
              readOnly: true
            - mountPath: /longhorn
              name: longhorn
      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        allowPrivilegeEscalation: true
      volumes:
        - name: nfs
          hostPath:
            path: /mnt/fileserver/apps/homer
            type: Directory
        - name: longhorn
          existingVolumeClaim: homer-longhorn
  backoffLimit: 2