apiVersion: batch/v1
kind: Job
metadata:
  name: check-filepaths-databend
  namespace: infra
spec:
  template:
    metadata:
      namespace: infra
    spec:
      containers:
        - name: databend
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - ls /local/meta/ && ls /local/query/ && ls /local/logs/
          volumeMounts:
            - mountPath: /local
              name: local
              readOnly: true
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 1001
      volumes:
        - name: local
          hostPath:
            path: /mnt/tera/vols/databend
            type: Directory
  backoffLimit: 3