apiVersion: batch/v1
kind: Job
metadata:
  name: db-user
  namespace: infra
spec:
  template:
    metadata:
      namespace: infra
    spec:
      containers:
        - image: bitnami/postgresql
          imagePullPolicy: IfNotPresent
          name: postgres
          command:
            - "/bin/bash"
            - "-c"
            - "echo \"SELECT 'CREATE ROLE $DB_USER LOGIN PASSWORD ''$DB_PASS'';' WHERE NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$DB_USER')\\gexec\" | psql -h $DB_HOST -U postgres && echo \"SELECT 'CREATE DATABASE $DB_NAME OWNER $DB_USER' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$DB_NAME')\\gexec\" | psql -h $DB_HOST -U postgres"
          env:
            - name: DB_NAME
              value: grafana
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-hosts
                  key: DB_HOSTNAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-secrets
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: grafana-secrets
                  key: DB_PASS
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-creds
                  key: postgres-password
      restartPolicy: Never
  backoffLimit: 3