apiVersion: batch/v1
kind: Job
metadata:
  name: fetch-files-job
  namespace: infra
spec:
  template:
    metadata:
      namespace: infra
    spec:
      containers:
        - image: secoresearch/rsync
          imagePullPolicy: IfNotPresent
          name: rsync
          env:
            - name: RSYNC_SOURCE
              value: /nfs 
            - name: RSYNC_TARGET
              value: /local
            - name: RSYNC_OPTIONS
              value: "-avrz"
          volumeMounts:
            - mountPath: /nfs
              name: nfs
            - mountPath: /local
              name: local
      restartPolicy: Never
      volumes:
        - name: nfs
          hostPath:
            path: /mnt/fileserver/rke2/main
            type: Directory
        - name: local
          hostPath:
            path: /home/homesys/rsync
            type: DirectoryOrCreate
  backoffLimit: 3